# Generated by Django 5.0.7 on 2024-08-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0002_rename_departments_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
    ]
