# Generated by Django 5.0.7 on 2024-08-23 12:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0003_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract', models.TextField(help_text='Abstract of the project (up to 200 words)', max_length=200)),
                ('keywords', models.CharField(help_text='Keywords (5-6, comma separated)', max_length=255)),
                ('informed_hod', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', help_text='Have you informed your HoD about this proposal?', max_length=3)),
                ('upload_hod_consent', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', help_text='Would you like to upload the reviews and consent from departmental HoD?', max_length=3)),
                ('hod_consent_pdf', models.FileField(blank=True, help_text='Upload PDF file. Max 10 MB.', null=True, upload_to='hod_consent/')),
            ],
            options={
                'verbose_name': 'Project Proposal',
                'verbose_name_plural': 'Project Proposals',
            },
        ),
        migrations.CreateModel(
            name='PrincipleInvestigator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PSRN', models.CharField(max_length=500)),
                ('Name_PI', models.CharField(max_length=500)),
                ('Designation_PI', models.CharField(max_length=500)),
                ('superannuation_date', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2014), django.core.validators.MaxValueValidator(2074)])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principle_investigators', to='Research.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principle_investigators', to='Research.organization')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EndorsementForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('Government', 'Government'), ('Industry Sponsored Project', 'Industry Sponsored Project'), ('Consultancy Project', 'Consultancy Project'), ('International Project', 'International Project'), ('Alumni Project', 'Alumni Project')], max_length=100)),
                ('funding_agency', models.CharField(max_length=500)),
                ('funding_scheme', models.CharField(blank=True, max_length=500, null=True)),
                ('funding_agency_type', models.CharField(choices=[('Government Project', 'Government Project'), ('Non-Governmental Organization in India', 'Non-Governmental Organization in India'), ('International', 'International'), ('Industry', 'Industry')], max_length=100)),
                ('CAPEX', models.PositiveIntegerField()),
                ('OPEX', models.PositiveIntegerField()),
                ('total_budget_requested', models.PositiveIntegerField()),
                ('budget_split', models.TextField(blank=True, null=True)),
                ('submission_type', models.CharField(choices=[('Online (Email submission)', 'Online (Email submission)'), ('Online (Portal submission)', 'Online (Portal submission)'), ('Offline (postal submission)', 'Offline (postal submission)')], max_length=100)),
                ('project_duration', models.PositiveIntegerField()),
                ('last_date_for_submission', models.DateField()),
                ('commencement_date_of_project', models.DateField()),
                ('endorsement_required', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', help_text='Is an Endorsement form required?', max_length=3)),
                ('endorsement_template', models.FileField(blank=True, help_text='Upload 1 supported file: doc/docx/pdf. Max 10 MB.', null=True, upload_to='endorsement_templates/')),
                ('additional_comments', models.TextField(blank=True, help_text='Any additional comments', null=True)),
                ('Co_PI1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endorsements_as_copi1', to='Research.principleinvestigator')),
                ('Co_PI2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endorsements_as_copi2', to='Research.principleinvestigator')),
                ('Co_PI3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endorsements_as_copi3', to='Research.principleinvestigator')),
                ('Co_PI4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endorsements_as_copi4', to='Research.principleinvestigator')),
                ('Co_PI5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endorsements_as_copi5', to='Research.principleinvestigator')),
                ('Co_PI6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endorsements_as_copi6', to='Research.principleinvestigator')),
                ('project_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='Research.projectproposal')),
            ],
            options={
                'verbose_name': 'Endorsement Form',
                'verbose_name_plural': 'Endorsement Forms',
            },
        ),
    ]
