# Generated by Django 5.0.7 on 2024-08-23 15:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0005_endorsementform_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endorsementform',
            name='project_proposal',
        ),
        migrations.AddField(
            model_name='endorsementform',
            name='Designation_PI',
            field=models.CharField(default='Not Provided', max_length=500),
        ),
        migrations.AddField(
            model_name='endorsementform',
            name='Name_PI',
            field=models.CharField(default='Not Provided', max_length=500),
        ),
        migrations.AddField(
            model_name='endorsementform',
            name='PSRN',
            field=models.CharField(default='Not Provided', max_length=500),
        ),
        migrations.AddField(
            model_name='endorsementform',
            name='Project_Title',
            field=models.CharField(default='Untitled Project', max_length=500),
        ),
        migrations.AddField(
            model_name='endorsementform',
            name='add_project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='endorsement_forms', to='Research.projectproposal'),
        ),
        migrations.AddField(
            model_name='endorsementform',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='endorsement_forms', to='Research.department'),
        ),
        migrations.AddField(
            model_name='endorsementform',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='endorsement_forms', to='Research.organization'),
        ),
        migrations.AddField(
            model_name='endorsementform',
            name='proposal_file',
            field=models.FileField(default=None, help_text='Upload 1 supported file: PDF. Max 10 MB.', upload_to='project_proposals/'),
        ),
        migrations.AddField(
            model_name='endorsementform',
            name='superannuation_date',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2014), django.core.validators.MaxValueValidator(2024)]),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='Unknown Department', max_length=500),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='CAPEX',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='Co_PI1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_pi1_forms', to='Research.principleinvestigator'),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='Co_PI2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_pi2_forms', to='Research.principleinvestigator'),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='Co_PI3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_pi3_forms', to='Research.principleinvestigator'),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='Co_PI4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_pi4_forms', to='Research.principleinvestigator'),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='Co_PI5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_pi5_forms', to='Research.principleinvestigator'),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='Co_PI6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_pi6_forms', to='Research.principleinvestigator'),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='OPEX',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='funding_agency',
            field=models.CharField(default='Not Provided', max_length=500),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='funding_agency_type',
            field=models.CharField(choices=[('Government Project', 'Government Project'), ('Non-Governmental Organization in India', 'Non-Governmental Organization in India'), ('International', 'International'), ('Industry', 'Industry')], default='Industry', max_length=100),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='project_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='project_type',
            field=models.CharField(choices=[('Government', 'Government'), ('Industry Sponsored Project', 'Industry Sponsored Project'), ('Consultancy Project', 'Consultancy Project'), ('International Project', 'International Project'), ('Alumni Project', 'Alumni Project')], default='Government', max_length=100),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='submission_type',
            field=models.CharField(choices=[('Online (Email submission)', 'Online (Email submission)'), ('Online (Portal submission)', 'Online (Portal submission)'), ('Offline (postal submission)', 'Offline (postal submission)')], default='Online (Email submission)', max_length=100),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='total_budget_requested',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='Unknown Organization', max_length=500),
        ),
        migrations.AlterField(
            model_name='principleinvestigator',
            name='Designation_PI',
            field=models.CharField(default='Not Provided', max_length=500),
        ),
        migrations.AlterField(
            model_name='principleinvestigator',
            name='Name_PI',
            field=models.CharField(default='Not Provided', max_length=500),
        ),
        migrations.AlterField(
            model_name='principleinvestigator',
            name='PSRN',
            field=models.CharField(default='Not Provided', max_length=500),
        ),
        migrations.AlterField(
            model_name='principleinvestigator',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='principle_investigators', to='Research.department'),
        ),
        migrations.AlterField(
            model_name='principleinvestigator',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='principle_investigators', to='Research.organization'),
        ),
        migrations.AlterField(
            model_name='principleinvestigator',
            name='superannuation_date',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2014), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
