# Generated by Django 5.0.7 on 2024-08-23 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0006_remove_endorsementform_project_proposal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='principleinvestigator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principle_investigators', to=settings.AUTH_USER_MODEL),
        ),
    ]
