# Generated by Django 5.0.7 on 2024-08-24 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0007_alter_principleinvestigator_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endorsementform',
            name='add_project',
        ),
        migrations.AddField(
            model_name='endorsementform',
            name='abstract',
            field=models.TextField(default=None, help_text='Abstract of the project (up to 200 words)', max_length=200),
        ),
        migrations.AddField(
            model_name='endorsementform',
            name='hod_consent_pdf',
            field=models.FileField(blank=True, help_text='Upload PDF file. Max 10 MB.', null=True, upload_to='hod_consent/'),
        ),
        migrations.AddField(
            model_name='endorsementform',
            name='informed_hod',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', help_text='Have you informed your HoD about this proposal?', max_length=3),
        ),
        migrations.AddField(
            model_name='endorsementform',
            name='keywords',
            field=models.CharField(default=None, help_text='Keywords (5-6, comma separated)', max_length=255),
        ),
        migrations.AddField(
            model_name='endorsementform',
            name='upload_hod_consent',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', help_text='Would you like to upload the reviews and consent from departmental HoD?', max_length=3),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='principleinvestigator',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ProjectProposal',
        ),
    ]
