# Generated by Django 5.0.7 on 2024-08-24 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0008_remove_endorsementform_add_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipment', models.PositiveIntegerField(default=0)),
                ('Consumables', models.PositiveIntegerField(default=0)),
                ('Fellowship', models.PositiveIntegerField(default=0)),
                ('Contingency', models.PositiveIntegerField(default=0)),
                ('Travel', models.PositiveIntegerField(default=0)),
                ('Field_Testing', models.PositiveIntegerField(default=0)),
                ('Miscellaneous', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Research.endorsementform')),
            ],
        ),
    ]
