# Generated by Django 5.0.7 on 2024-08-24 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0009_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='Consumables',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Contingency',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Equipment',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Fellowship',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Field_Testing',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Miscellaneous',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Travel',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='project',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Research.endorsementform'),
        ),
    ]
