# Generated by Django 5.0.7 on 2024-08-24 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0010_alter_budget_consumables_alter_budget_contingency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecievedAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipment', models.PositiveIntegerField()),
                ('Consumables', models.PositiveIntegerField()),
                ('Fellowship', models.PositiveIntegerField()),
                ('Contingency', models.PositiveIntegerField()),
                ('Travel', models.PositiveIntegerField()),
                ('Field_Testing', models.PositiveIntegerField()),
                ('Miscellaneous', models.PositiveIntegerField()),
                ('project', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Research.endorsementform')),
            ],
        ),
    ]
