# Generated by Django 5.0.7 on 2024-08-24 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0011_recievedamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('installment_year', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Financial_Year', to='Research.financialyear')),
                ('project', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Research.endorsementform')),
            ],
        ),
    ]
