# Generated by Django 5.0.7 on 2024-08-24 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0012_financialyear_installment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Research.endorsementform'),
        ),
    ]
