# Generated by Django 5.0.7 on 2024-08-24 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0013_alter_installment_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenditure_type', models.CharField(choices=[('Consumables', 'Consumables'), ('Fellowship', 'Fellowship'), ('Contingency', 'Contingency'), ('Travel', 'Travel'), ('Field Testing', 'Field Testing'), ('Miscellaneous', 'Miscellaneous')], max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('Recurring', 'Recurring'), ('Non-Recurring', 'Non-Recurring')], max_length=100)),
                ('installment_year', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='financialyear', to='Research.financialyear')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Research.endorsementform')),
            ],
        ),
    ]
