# Generated by Django 5.0.7 on 2024-08-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0014_expenditure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='installment_year',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='Expenditure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='type',
            field=models.CharField(blank=True, choices=[('Recurring', 'Recurring'), ('Non-Recurring', 'Non-Recurring')], max_length=100, null=True),
        ),
    ]
