# Generated by Django 5.0.7 on 2024-08-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0015_remove_expenditure_installment_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endorsementform',
            name='superannuation_date',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
