# Generated by Django 5.0.7 on 2024-08-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0016_alter_endorsementform_superannuation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='sanctionorder',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
