# Generated by Django 5.0.7 on 2024-08-25 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0017_budget_sanctionorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recievedamount',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Research.endorsementform'),
        ),
    ]
