# Generated by Django 5.0.7 on 2024-08-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0018_alter_recievedamount_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='sanctiondate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
