# Generated by Django 5.0.7 on 2024-08-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0019_budget_sanctiondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='endorsementform',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
