# Generated by Django 5.0.7 on 2024-08-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0020_endorsementform_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endorsementform',
            name='completed',
        ),
        migrations.AddField(
            model_name='endorsementform',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=20),
        ),
    ]
