# Generated by Django 5.0.7 on 2024-08-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0021_remove_endorsementform_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endorsementform',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endorsementform',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
