# Generated by Django 5.0.7 on 2024-08-28 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0022_endorsementform_end_date_endorsementform_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='endorsementform',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Year', to='Research.financialyear'),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='CAPEX',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='Designation_PI',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='Name_PI',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='OPEX',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='PSRN',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='Project_Title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='abstract',
            field=models.TextField(blank=True, help_text='Abstract of the project (up to 200 words)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='commencement_date_of_project',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endorsement_forms', to='Research.department'),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='endorsement_required',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], help_text='Is an Endorsement form required?', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='funding_agency',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='funding_agency_type',
            field=models.CharField(blank=True, choices=[('Government Project', 'Government Project'), ('Non-Governmental Organization in India', 'Non-Governmental Organization in India'), ('International', 'International'), ('Industry', 'Industry')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='informed_hod',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], help_text='Have you informed your HoD about this proposal?', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='keywords',
            field=models.CharField(blank=True, help_text='Keywords (5-6, comma separated)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='last_date_for_submission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endorsement_forms', to='Research.organization'),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='project_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='project_type',
            field=models.CharField(blank=True, choices=[('Government', 'Government'), ('Industry Sponsored Project', 'Industry Sponsored Project'), ('Consultancy Project', 'Consultancy Project'), ('International Project', 'International Project'), ('Alumni Project', 'Alumni Project')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='proposal_file',
            field=models.FileField(blank=True, help_text='Upload 1 supported file: PDF. Max 10 MB.', null=True, upload_to='project_proposals/'),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='submission_type',
            field=models.CharField(blank=True, choices=[('Online (Email submission)', 'Online (Email submission)'), ('Online (Portal submission)', 'Online (Portal submission)'), ('Offline (postal submission)', 'Offline (postal submission)')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='total_budget_requested',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='endorsementform',
            name='upload_hod_consent',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], help_text='Would you like to upload the reviews and consent from departmental HoD?', max_length=3, null=True),
        ),
    ]
