# Generated by Django 5.0.7 on 2024-08-30 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0023_endorsementform_year_alter_endorsementform_capex_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinYearBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipment', models.PositiveIntegerField()),
                ('Consumables', models.PositiveIntegerField()),
                ('Fellowship', models.PositiveIntegerField()),
                ('Contingency', models.PositiveIntegerField()),
                ('Travel', models.PositiveIntegerField()),
                ('Field_Testing', models.PositiveIntegerField()),
                ('Miscellaneous', models.PositiveIntegerField()),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Research.endorsementform')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Research.financialyear')),
            ],
        ),
    ]
