# Generated by Django 5.0.7 on 2024-08-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0024_finyearbudget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finyearbudget',
            name='Consumables',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finyearbudget',
            name='Contingency',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finyearbudget',
            name='Equipment',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finyearbudget',
            name='Fellowship',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finyearbudget',
            name='Field_Testing',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finyearbudget',
            name='Miscellaneous',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finyearbudget',
            name='Travel',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
