# Generated by Django 5.0.7 on 2024-08-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0025_alter_finyearbudget_consumables_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='expenditure_type',
            field=models.CharField(choices=[('Equipment', 'Equipment'), ('Consumables', 'Consumables'), ('Fellowship', 'Fellowship'), ('Contingency', 'Contingency'), ('Travel', 'Travel'), ('Field Testing', 'Field Testing'), ('Miscellaneous', 'Miscellaneous')], max_length=100),
        ),
    ]
