# Generated by Django 5.0.7 on 2024-08-31 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0026_alter_expenditure_expenditure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Research.financialyear'),
        ),
    ]
