# Generated by Django 5.1.2 on 2024-11-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Research", "0027_expenditure_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="endorsementform",
            name="sanction_letter",
            field=models.FileField(
                blank=True,
                help_text="Upload 1 supported file: PDF. Max 10 MB.",
                null=True,
                upload_to="sanction_letter/",
            ),
        ),
    ]
