# Generated by Django 5.1.2 on 2024-11-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Research", "0028_endorsementform_sanction_letter"),
    ]

    operations = [
        migrations.AddField(
            model_name="installment",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Upload 1 supported file: PDF. Max 10 MB.",
                null=True,
                upload_to="file/",
            ),
        ),
    ]
